[workspace]
resolver = "2"
members = [
    "controller",
    "model",
    "view",
]

[profile.dev]
opt-level=0
debug=2
incremental=false

[profile.profiling]
inherits = "dev"
opt-level=3
debug=2
incremental=true

[profile.release]
opt-level=3
debug=0
incremental=true
