[package]
name = "transfer-window-common"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
nalgebra-glm = "0.18.0"
kurbo = "0.11.0"
tracy-client = { version = "0.17.0", optional = true }
tracing-tracy = { version = "0.11.0", optional = true }

[lints]
workspace = true